{"id": "CVE-2020-25032", "package": "pypi:flask-cors", "package_type": "flask-cors_project", "package_usage": "optional", "version": "<3.0.9", "fix_version": "3.0.9", "severity": "HIGH", "cvss_score": "7.5", "short_description": "An issue was discovered in Flask-CORS (aka CORS Middleware for Flask) before 3.0.9. It allows ../ directory traversal to access private resources because resource matching does not ensure that pathnames are in a canonical format.", "related_urls": ["https://github.com/corydolphin/flask-cors/releases/tag/3.0.9", "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00028.html", "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00032.html", "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00039.html", "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00048.html", "https://www.debian.org/security/2020/dsa-4775"]}
